/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucoesRouteImport } from './routes/solucoes'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as ProjetoSlugRouteImport } from './routes/projeto.$slug'
import { Route as PortfolioSlugRouteImport } from './routes/portfolio.$slug'

const SolucoesRoute = SolucoesRouteImport.update({
  id: '/solucoes',
  path: '/solucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetoSlugRoute = ProjetoSlugRouteImport.update({
  id: '/projeto/$slug',
  path: '/projeto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioSlugRoute = PortfolioSlugRouteImport.update({
  id: '/portfolio/$slug',
  path: '/portfolio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projetos': typeof ProjetosRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/projeto/$slug': typeof ProjetoSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projetos': typeof ProjetosRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/projeto/$slug': typeof ProjetoSlugRoute
  '/portfolio': typeof PortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projetos': typeof ProjetosRoute
  '/servicos': typeof ServicosRoute
  '/sobre': typeof SobreRoute
  '/solucoes': typeof SolucoesRoute
  '/portfolio/$slug': typeof PortfolioSlugRoute
  '/projeto/$slug': typeof ProjetoSlugRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projetos'
    | '/servicos'
    | '/sobre'
    | '/solucoes'
    | '/portfolio/$slug'
    | '/projeto/$slug'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projetos'
    | '/servicos'
    | '/sobre'
    | '/solucoes'
    | '/portfolio/$slug'
    | '/projeto/$slug'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/projetos'
    | '/servicos'
    | '/sobre'
    | '/solucoes'
    | '/portfolio/$slug'
    | '/projeto/$slug'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjetosRoute: typeof ProjetosRoute
  ServicosRoute: typeof ServicosRoute
  SobreRoute: typeof SobreRoute
  SolucoesRoute: typeof SolucoesRoute
  PortfolioSlugRoute: typeof PortfolioSlugRoute
  ProjetoSlugRoute: typeof ProjetoSlugRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solucoes': {
      id: '/solucoes'
      path: '/solucoes'
      fullPath: '/solucoes'
      preLoaderRoute: typeof SolucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeto/$slug': {
      id: '/projeto/$slug'
      path: '/projeto/$slug'
      fullPath: '/projeto/$slug'
      preLoaderRoute: typeof ProjetoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$slug': {
      id: '/portfolio/$slug'
      path: '/portfolio/$slug'
      fullPath: '/portfolio/$slug'
      preLoaderRoute: typeof PortfolioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjetosRoute: ProjetosRoute,
  ServicosRoute: ServicosRoute,
  SobreRoute: SobreRoute,
  SolucoesRoute: SolucoesRoute,
  PortfolioSlugRoute: PortfolioSlugRoute,
  ProjetoSlugRoute: ProjetoSlugRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
